apiVersion: v1
kind: Secret
metadata:
  name: image-updater
  namespace: argocd-test
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com/Akshaya-Parthi/image-updater.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDX6DRJEaqw7wSEe+HTEYustEi1FmKJhHNurTKk83vFwgAAAKjByOEqwcjh
    KgAAAAtzc2gtZWQyNTUxOQAAACDX6DRJEaqw7wSEe+HTEYustEi1FmKJhHNurTKk83vFwg
    AAAEAvEaPn3HUsVFGz9cSRc9YJXNAzhzQzWztThtvaFfN8o9foNEkRqrDvBIR74dMRi6y0
    SLUWYomEc26tMqTze8XCAAAAHmFrc2hheWFwYXJ0aGliYW4xOTk5QGdtYWlsLmNvbQECAw
    QFBgc=
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"
